//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSensor
    {
        public int SensorID { get; set; }
        public string SensorName { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSensorData
    {
        public int Id { get; set; }
        public string sensorID { get; set; }
        public string sensorName { get; set; }
        public string applicationID { get; set; }
        public string networkID { get; set; }
        public string dataMessageGUID { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> messageDate { get; set; }
        public string rawData { get; set; }
        public string dataType { get; set; }
        public string dataValue { get; set; }
        public string plotValues { get; set; }
        public string plotLabels { get; set; }
        public string batteryLevel { get; set; }
        public string signalStrength { get; set; }
        public string pendingChange { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSensorData1
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string dataMessageGUID { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSensorData2
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string dataMessageGUID { get; set; }
    }
}
namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSensorData3
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string dataMessageGUID { get; set; }
    }
}
