//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DriveThruEntities : DbContext
    {
        public DriveThruEntities()
            : base("name=DriveThruEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblSensor> tblSensors { get; set; }
        public virtual DbSet<tblSensorData> tblSensorDatas { get; set; }
        public virtual DbSet<tblSensorData1> tblSensorData1 { get; set; }
        public virtual DbSet<tblSensorData2> tblSensorData2 { get; set; }
        public virtual DbSet<tblSensorData3> tblSensorData3 { get; set; }
    }
}
